[project]
name = "vet_chatbot"
version = "2.0.0"
requires-python = ">=3.13.11"
dependencies = ["crewai", "langchain_groq", "streamlit", "litellm"]

[project.optional-dependencies]
dev = [
		"ruff", "mypy", "tombi", "pip-tools"
]
